config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :products do
    resources :comments
  end
  resources :payments
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'
  post 'payments/create'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :new, :create]
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments

  # validation
  validates :name, presence: true

  def average_rating
    comments.average(:rating).to_f
  end
  


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    # @products = Product.all
    if params[:q] && Rails.env.production?
     search_term = params[:q]
     @products = Product.where('name ilike ? OR description ilike ?', "%#{search_term}%", "%#{search_term}%")
    elsif params[:q] && Rails.env.development?
     search_term = params[:q]
     @products = Product.where('name LIKE ? OR description LIKE ?', "%#{search_term}%", "%#{search_term}%")
      #return filtered list here
    else
     @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.all.order("created_at DESC") #.paginate(:page => params[:page], :per_page => 5)
    @comments = @comments.paginate(:page => params[:page], :per_page => 5)
  end



  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s,:number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, :step => 0.01 %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class =>"btn btn-default"%>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div class="new-review--frame">
  <% if signed_in? %>
    <h4 class="new-review--header">Add a review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <p>
        <%= f.label :body, "Comments" %><br>
        <%= f.text_area :body %>
      </p>
      <div class="new-review--rating">
        <p>
          <%= f.label :rating %><br>
          <div class="rating"></div>
        </p>
      </div>
      <p>
        <%= f.submit "Submit", class: "btn btn-default", id: "submit-button-comment" %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
  <div class="product-card">
  

  <div class="product-card-frame">
    <%= image_tag product.image_url, :class => "product-card--img" %>
  </div>
  <div class="product-card--price">
    <p><%= product.price%>€</p>
  </div>
  <div class="product-card--name">
    <p><%=h truncate(product.name, :length => 40, omission: '') {link_to '...', product, :class => 'truncate_link'} %></p>
  </div>
  <div>
    <%=h truncate(product.description, :length => 80, omission: '') {link_to '...read more', product, :class => 'truncate_link'} %>
  </div>
  
  
    

  <div class="product-card--button">
    <div class="btn-group btn-group-tools">
      <%= link_to 'Show', product, :class => "btn btn-default" %>
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Show', product %></li>
        <li><%= link_to 'Edit', edit_product_path(product) %></li>
        <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
  </div>

  </div>
</div>

app/views/products/_product_reviews.html.erb
<div class="product_reviews">
  <% @comments.each do |comment| %>
    <div class="row product_reviews--row">
      <hr>
      <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
      
      <% if signed_in? && current_user.admin?  %>
        <%= link_to 'Destroy', product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
      <% end -%>
    </div>
  <% end %>


  <%= will_paginate @comments %>

</div>

app/views/products/_product_reviews_just_created.html.erb
<div class="product_reviews">
  <% @comments.limit(1).each do |comment| %>
    <div class="row product_reviews--row">
      <hr>
      <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
      
      <% if signed_in? && current_user.admin?  %>
        <%= link_to 'Destroy', product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
      <% end -%>
    </div>
  <% end %>

</div>

app/views/products/edit.html.erb
<div class="width_frame">
  <h1>Editing Product</h1>

  <%= render 'form' %>


  <div class="btn-group-frame">
    <div class="btn-group" role="group">
      <%= link_to 'Show', @product, :class => "btn btn-default" %>
      <%= link_to 'Back', products_path, :class => "btn btn-default" %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="width_frame">
  <%# cache(cache_key_for_products) do %>
  <div class="recent-products-header">
    <p>products</p>
  </div>

  <div class="row">
  <%# cache(p) do %>
    <%= render @products %>
  <%# end %>
  </div>

  <div class="recent-products-header products-header-space">
    <p>add products</p>
  </div>  
  <%= link_to 'New Product', new_product_path, :class => "btn btn-default product_button" %>

  <%# end %>
</div>

<%= render partial: "shared/footer" %>

app/views/products/new.html.erb
<div class="width_frame">
  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path, :class => "btn btn-danger back_button" %>
</div>

app/views/products/show.html.erb
<div class="width_frame review_bottom">
  
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
      <div class="show_room">
      <%= image_tag @product.image_url, :'data-action' => 'zoom' %>
      </div>
    </div>
    
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Image url:</strong>
        <%= @product.image_url %>
      </p>

      <p>
        <strong>Colour:</strong>
        <%= @product.colour %>
      </p>

      <p class="unit-float">
        <strong>Price:</strong>
        <%= @product.price %> <p>€</p>
      </p>

      <p>
        <strong>Average Rating:</strong>
        <span class="rated" data-score="<%= @product.average_rating %>"></span>
      </p>
      
      <%= form_tag '/payments/create' do %>
        <%= render partial: "shared/stripe_checkout_button" %>
      <% end %>

    </div>

  </div>
  
  
  

  <div class="btn-group-frame">
    <div class="btn-group" role="group">
      <%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-default" %>
      <%= link_to 'Back', products_path, :class => "btn btn-default" %>
    </div>
  </div>


  <%= render 'new_comment' %>
<div id="product-review-comments">
</div>
  <%= render 'product_reviews' %>
  
</div>

<%= render partial: "shared/footer" %>