config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :products do
    resources :comments
  end
  resources :payments
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'
  post 'payments/create'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MyNewApp</title>
  <%= favicon_link_tag 'favicon.png' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-static-top navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <%= link_to "idea manufactory", root_path, :class => "navbar-brand" %> -->
        
        <%= link_to :back, :class => "navbar-brand brand-back" do %>
        <span class="glyphicon glyphicon-chevron-left"></span>
        <% end %>
        <%= link_to root_path, :class => "navbar-brand" do %>
        <span>idea manufactory</span>
        <% end %>

      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Contact", static_pages_contact_path %></li>
          <% if user_signed_in? %>
            <li class="log-button">
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
          <% else %>
            <li class="log-button">
            <%= link_to('Login', new_user_session_path)  %>  
            </li>
          <% end %>
        </ul>
        <div class="search-frame">
          <%= form_tag("/products", method: "get", :class => "search-field-header") do %>
            <%= text_field_tag(:q, nil , :class => "text-field-searchbox") %>
            <%= submit_tag("Search", :class => "text-field-searchbutton") %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  
  <!-- message at log-in -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>  

<%= yield %>

</body>
</html>